version: '3.8'
networks:
    webnet:
services:
    proxy:
        container_name: proxy
        image: nginx:latest
        build: 
            context: ./nginx
            dockerfile: Dockerfile
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
            - 443:443           
        networks:
            - webnet
        depends_on:
            - flask
            - static
    flask:
        build:
            context: ./flask
            dockerfile: Dockerfile
        container_name: flask
        volumes:
            - ./flask:/code/
        environment:
            - FLASK_APP=./main.py
        command : flask run
        ports:
            - 8000:5000
        networks:
            - webnet
        depends_on:
            - redis
    redis:
        image: "redis:latest"
        container_name: redis
        restart: always
        expose:
            - '6379'
        networks:
            - webnet
    static:
        container_name: static
        build:
            context: ./static
            dockerfile: Dockerfile
        expose:
            - "80"
        networks:
            - webnet
    

   